[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
archives = "4VXdnDCoG585gSRvR7S3ZtjZQjGinnyt8waBrCEWUGcm"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/evaldocunhafilho/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
