[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
archives_sol = "7bYR2BPEbLE5uR22XsUito5GWeDMJAgnocgU4r88NNMA"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/evaldocunhafilho/.config/solana/id.json"

[scripts]
test = "yarn run mocha -t 1000000 tests/"
